backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - { name: path, label: Path, widget: "string" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "events"
    label: "Events"
    description: "event dates, location, and presenter information."
    folder: "src/pages/events"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "event" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: Presenters,
          name: presenters,
          required: true,
          widget: list,
          fields:
            [
              { label: Name, name: name, required: true, widget: string },
              {
                label: Presentation Title,
                name: presentationTitle,
                required: false,
                widget: string,
              },
              {
                label: Image,
                name: image,
                required: false,
                hint: "If an image isn't specified, a default headshot placeholder image will be used",
                widget: image,
              },
              { label: Text, name: text, required: true, widget: text },
              {
                label: Links,
                name: links,
                required: false,
                widget: list,
                fields:
                  [
                    { label: Text, name: linkText, widget: string },
                    { label: URL, name: linkURL, widget: string },
                  ],
              },
            ],
        }
      - {
          label: "Location",
          name: "location",
          required: true,
          widget: "object",
          fields:
            [
              { label: "Name", name: "name", widget: "string" },
              { label: "Google Maps Link", name: "mapsLink", widget: "string" },
              { label: "Latitude", name: "mapsLatitude", widget: "number", valueType: "float" },
              { label: "Longitude", name: "mapsLongitude", widget: "number", valueType: "float" },
            ],
        }